"use strict";(()=>{var e={};e.id=890,e.ids=[890],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},2048:e=>{e.exports=require("fs")},2615:e=>{e.exports=require("http")},8791:e=>{e.exports=require("https")},5315:e=>{e.exports=require("path")},8621:e=>{e.exports=require("punycode")},6162:e=>{e.exports=require("stream")},7360:e=>{e.exports=require("url")},1764:e=>{e.exports=require("util")},2623:e=>{e.exports=require("worker_threads")},1568:e=>{e.exports=require("zlib")},7561:e=>{e.exports=require("node:fs")},4492:e=>{e.exports=require("node:stream")},2477:e=>{e.exports=require("node:stream/web")},4106:(e,r,t)=>{t.r(r),t.d(r,{originalPathname:()=>h,patchFetch:()=>v,requestAsyncStorage:()=>c,routeModule:()=>x,serverHooks:()=>m,staticGenerationAsyncStorage:()=>q});var o={};t.r(o),t.d(o,{OPTIONS:()=>l,POST:()=>d,runtime:()=>u});var i=t(9303),p=t(8716),a=t(670),s=t(4526),n=t(5242);let u="nodejs";function l(){return(0,s.YM)()}async function d(e){try{let r=await e.json(),t=`Ти досвідчений Full Stack developer і викладач курсу. Поясни тему студенту чітко і по суті.

Формат відповіді (Markdown):
1. **Коротке пояснення** — що це таке і навіщо (2-3 речення)
2. **Ключові концепції** — найважливіші поняття які треба знати
3. **Приклад коду** — короткий практичний приклад (якщо є що показати)
4. **Що вчити** — конкретні кроки для самостійного опрацювання

Відповідай українською. Будь конкретним, уникай води.`,o=await (0,n.xg)(t,[{role:"user",content:`Модуль: ${r.moduleTitle}
Тема: ${r.topic}`}],1400);return(0,s.AV)(200,{explanation:o})}catch(e){return(0,s.VR)(e)}}let x=new i.AppRouteRouteModule({definition:{kind:p.x.APP_ROUTE,page:"/api/topic/explain/route",pathname:"/api/topic/explain",filename:"route",bundlePath:"app/api/topic/explain/route"},resolvedPagePath:"/Users/svatoslavarosenko/learning-web-app/app/api/topic/explain/route.ts",nextConfigOutput:"",userland:o}),{requestAsyncStorage:c,staticGenerationAsyncStorage:q,serverHooks:m}=x,h="/api/topic/explain/route";function v(){return(0,a.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:q})}}};var r=require("../../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),o=r.X(0,[276,972,214,325],()=>t(4106));module.exports=o})();